package models

// Code generated by TORM; DO NOT EDIT.
type ProjectType string

const (
	ProjectTypeDiploma ProjectType = "diploma"
	ProjectTypeClass   ProjectType = "class"
	ProjectTypeExtra   ProjectType = "extra"
)

type Category string

const (
	CategorySoftware  Category = "software"
	CategoryNetworks  Category = "networks"
	CategoryEmbedded  Category = "embedded"
	CategoryBattlebot Category = "battlebot"
)
