package models

// Code generated by TORM; DO NOT EDIT.

import (
	"time"
)

type Project struct {
	Id               int
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        time.Time
	Name             string
	Description      string
	Type             ProjectType
	Category         Category
	Mentor           string
	VideoLink        string
	HasThumbnail     bool
	DemoLink         string
	GithubLink       string
	Creators         []Creator
	Pictures         []Picture
	VotesAsNetwork   []Vote
	VotesAsSoftware  []Vote
	VotesAsEmbedded  []Vote
	VotesAsBattleBot []Vote
}
