package models

// Code generated by TORM; DO NOT EDIT.

import (
	"time"
)

type Creator struct {
	Id        int
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt time.Time
	Name      string
	Email     string
	Phone     string
	Grade     int
	Class     string
	ProjectId int
}
