package models

// Code generated by TORM; DO NOT EDIT.

import (
	"time"
)

type Picture struct {
	Id          int
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   time.Time
	Url         string
	IsThumbnail bool
	ProjectId   int
}
