package models

// Code generated by TORM; DO NOT EDIT.

import (
	"time"
)

type Vote struct {
	Id          int
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   time.Time
	Name        string
	Email       string
	Verified    bool
	NetworksId  int
	SoftwareId  int
	EmbeddedId  int
	BattleBotId int
}
